@echo off

echo Compilando arquivos .java...

echo passo 1 de 5...
for %%f in (src\categorias\*.java) do javac -d out -sourcepath src %%f
echo passo 2 de 5...
for %%f in (src\app\*.java) do javac -d out -sourcepath src %%f
echo passo 3 de 5...
for %%f in (src\app\telas\*.java) do javac -d out -sourcepath src %%f
echo passo 4 de 5...
for %%f in (src\app\UI\*.java) do javac -d out -sourcepath src %%f
echo passo 5 de 5...

echo Executando...
java -cp out app.GUI
pause